### ISSUE TITLE
Post install script does not observe system proxy

### ISSUE THREAD

**Issue by ArktekniK** [felicienfrancois/node-resourcehacker#4]
Hi, it looks like your post install script doesn't observe the node proxy settings.
Therefore, installation fails with:

Downloading ResourceHacker by Angus Johnson...
connect ECONNREFUSED 150.101.136.194:80

Thanks

**Comment by felicienfrancois** [comment]
Should be fixed now: https://github.com/felicienfrancois/node-resourcehacker/commit/4ec4f97655592bb9fa860eb95723f35d5c3e3375

Published v4.2.5 to npm.

Can you please retry with the latest release ?

**Comment by ArktekniK** [comment]
Hey, thanks for taking a look but I'm still seeing connection refused.
I'll take a look into it and get back to you when I have some time

**Comment by felicienfrancois** [comment]
- What is your operating system?
- How did you setup the proxy for npm?
- Have you an http_proxy or HTTP_PROXY environment variable set?

**Comment by felicienfrancois** [comment]
I made another change (now takes npm_config_proxy into account)
Published to npm (4.2.51).
